# Generated by Django 5.0.6 on 2024-06-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_products_customer_joined_on_customer_last_login_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
